#!/usr/bin/env bash
# install.sh — Install RiotBox for the current user (rootless, XDG layout).
# Lays the app tree into $XDG_DATA_HOME/riotbox and symlinks the entrypoint
# into a directory on your PATH. Re-runnable; never overwrites user config
# and never touches session dirs or git backups that share the data tree.
#
# Usage:
#   ./install.sh                  # entrypoint -> ~/.local/bin/riotbox
#   ./install.sh ~/.local/bin     # explicit (same as default)
#   ./install.sh ~/bin            # custom bin dir
set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION="$(cat "${SRC_DIR}/VERSION" 2>/dev/null || echo "unknown")"

DATA_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/riotbox"
CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/riotbox"
BIN_DIR="${1:-${HOME}/.local/bin}"

# Runtime app tree shipped to the data dir. Dev-only material (Taskfile,
# .taskfiles, tests, docs, nfpm.yaml, .github) is intentionally excluded.
# Top-level configs/ is also excluded: it is a host-specific build artifact
# regenerated by scripts/build.sh from the user's tool configs at build time.
#
# Each entry is removed from DATA_DIR before re-copying. Anything in DATA_DIR
# that is NOT in this list (notably session dirs, backups/, and any user
# additions) is preserved across upgrades — wiping DATA_DIR wholesale would
# destroy the safety backups described in README and silently lose work.
APP_PATHS=(bin libexec scripts agents container Containerfile .dockerignore VERSION)
APP_MARKER=".riotbox-app"

echo "Installing RiotBox ${VERSION} → ${DATA_DIR}"

# Refuse to touch a DATA_DIR that exists but does not look like a RiotBox
# install: a user could have pointed XDG_DATA_HOME at something with their
# own data, and we would rather error than wipe it. The marker file is
# created on first install and re-asserted on every upgrade.
if [[ -e "${DATA_DIR}" ]] && [[ ! -f "${DATA_DIR}/${APP_MARKER}" ]]; then
	# An existing tree without a marker that nevertheless contains all of
	# the known app paths is a pre-marker install. Treat it as ours so the
	# first upgrade past this commit succeeds without manual intervention.
	is_legacy_app_tree=true
	for p in "${APP_PATHS[@]}"; do
		[[ -e "${DATA_DIR}/${p}" ]] || {
			is_legacy_app_tree=false
			break
		}
	done
	if [[ "${is_legacy_app_tree}" != true ]]; then
		echo "ERROR: ${DATA_DIR} exists but is not a RiotBox install tree." >&2
		echo "       (no ${APP_MARKER} marker and missing expected app paths)" >&2
		echo "       Remove or move it manually if you really want to install here." >&2
		exit 1
	fi
fi

mkdir -p "${DATA_DIR}" "${BIN_DIR}" "${CONFIG_DIR}"

# Surgical removal of just the app tree entries — sessions and backups
# (also under DATA_DIR) survive. Replacing a file with a directory across
# upgrades works because we remove the old entry first.
for p in "${APP_PATHS[@]}"; do
	rm -rf "${DATA_DIR:?}/${p}"
done

for p in "${APP_PATHS[@]}"; do
	[[ -e "${SRC_DIR}/${p}" ]] || continue
	cp -a "${SRC_DIR}/${p}" "${DATA_DIR}/"
done
chmod +x "${DATA_DIR}/bin/riotbox"

# Marker file makes the next upgrade unambiguous about which tree it owns.
: >"${DATA_DIR}/${APP_MARKER}"

ln -sfn "${DATA_DIR}/bin/riotbox" "${BIN_DIR}/riotbox"
echo "  Entrypoint: ${BIN_DIR}/riotbox -> ${DATA_DIR}/bin/riotbox"

# ── Config stubs ─────────────────────────────────────────────────────────
# Seed commented stubs into the user's XDG config. Never overwrite existing
# files. Warn if a newer riotbox-config-version ships than is installed.
STUBS_DIR="${SRC_DIR}/scripts/configs"
for stub in config mounts.conf plugins.conf; do
	src="${STUBS_DIR}/${stub}"
	dst="${CONFIG_DIR}/${stub}"
	[[ -f "${src}" ]] || continue
	if [[ ! -f "${dst}" ]]; then
		cp "${src}" "${dst}"
		echo "  Config: ${dst} (created)"
	else
		shipped_ver="$(grep -m1 '^# riotbox-config-version:' "${src}" 2>/dev/null | awk '{print $NF}' || true)"
		installed_ver="$(grep -m1 '^# riotbox-config-version:' "${dst}" 2>/dev/null | awk '{print $NF}' || true)"
		if [[ -n "${shipped_ver}" ]] && [[ -n "${installed_ver}" ]] &&
			[[ "${shipped_ver}" -gt "${installed_ver}" ]] 2>/dev/null; then
			echo "  Config: ${dst} (exists, v${installed_ver} — v${shipped_ver} available)"
			echo "          Your config is preserved. To see what changed:"
			echo "            diff ${dst} ${src}"
			echo "          Merge new options manually, or back up and re-init:"
			echo "            mv ${dst} ${dst}.bak && cp ${src} ${dst}"
		else
			echo "  Config: ${dst} (exists, up to date)"
		fi
	fi
done

if ! echo "${PATH}" | tr ':' '\n' | grep -qx "${BIN_DIR}"; then
	echo "Note: ${BIN_DIR} is not in your PATH. Add it:"
	echo "  export PATH=\"${BIN_DIR}:\${PATH}\""
fi
