#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# copy-manifest-coverage.sh — assert every build-context COPY/ADD source in the
# Containerfile exists in the repo and is shipped by BOTH install manifests.
#
# Why this is a static check and not a build: `riotbox build` runs the
# Containerfile from the INSTALLED app tree (/opt/riotbox for a package,
# ${XDG_DATA_HOME}/riotbox for install.sh), not from the dev repo. A COPY whose
# source no manifest ships resolves in the repo and nowhere else, so the build
# stays green for the developer who added it and breaks for every user who
# installed from an rpm, a deb, or install.sh. `podman build` does not run in
# the dev container (docs/dev/context-mode.md), so nothing here would observe
# that — the Containerfile has to be checked as text against repo state.
#
# The two manifests are independent and both have to cover a source:
#   - nfpm.yaml `contents:` builds the rpm/deb payload.
#   - install.sh APP_PATHS copies the tree for a from-source install.
# packaging/ is in neither, deliberately — it holds nfpm maintainer scripts
# that run on the host, never from the install tree.
#
# Usage:  bash tests/lib/copy-manifest-coverage.sh [REPO_ROOT]   (default ".")
#
# REPO_ROOT must be a tree you trust: reconstructing APP_PATHS evals a line out
# of its install.sh (see below), so pointing this at an untrusted checkout runs
# shell from it.
#
# Prints "copy_manifest_coverage=pass (<n> sources, <m> exempt)" and exits 0
# when every source resolves; prints one "UNRESOLVED <source>: …" line per gap
# and exits 1 otherwise. Premise failures (an unreadable file, a manifest that
# parsed empty, a Containerfile with no COPY at all) exit 1 with "FAIL: …" so
# a parser that has stopped seeing anything cannot report a pass.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

repo_root="${1:-.}"
containerfile="${repo_root}/Containerfile"
nfpm_manifest="${repo_root}/nfpm.yaml"
installer="${repo_root}/install.sh"

for f in "${containerfile}" "${nfpm_manifest}" "${installer}"; do
	[[ -r "${f}" ]] || {
		echo "FAIL: cannot read ${f}"
		exit 1
	}
done

# Top-level configs/ is a host-specific build artifact regenerated by
# scripts/build.sh from the installing user's tool configs at `riotbox build`
# time. nfpm.yaml carries the same note where it declines to ship it.
EXEMPT_SOURCES=(configs)

# ── The shipped sets ─────────────────────────────────────────────────────────

# nfpm: only `./`-relative sources come out of the build context. The absolute
# ones (/opt/riotbox/bin/riotbox) are symlinks to paths a relative entry has
# already installed, so they ship nothing of their own.
# shellcheck disable=SC2312  # grep exits 1 when nothing matches; the empty-array check below is the handler
mapfile -t nfpm_ships < <(
	grep -oE '^[[:space:]]*-[[:space:]]+src:[[:space:]]+\./[^[:space:]]+' "${nfpm_manifest}" |
		sed -E 's#^.*\./##'
)
((${#nfpm_ships[@]} > 0)) || {
	echo "FAIL: parsed no relative src: entries out of ${nfpm_manifest} — the contents list moved or changed shape"
	exit 1
}

# install.sh: evaluated as a real bash array rather than pattern-matched out,
# so quoting and line continuations are read exactly the way install.sh reads
# them. The eval'd text is committed repo content, which every other check here
# already trusts as input — but it is a line range, not a parsed assignment, so
# anything sharing the closing-paren line would execute too. That is the reason
# for the trust note in the usage block above.
# Accumulation stops at the first line carrying the closing paren, the start
# line included — a sed range would not stop there and would sweep in the rest
# of the installer.
app_paths_decl="$(awk '/^APP_PATHS=\(/{f = 1} f {print} f && /\)/ {exit}' "${installer}")"
[[ -n "${app_paths_decl}" ]] || {
	echo "FAIL: no APP_PATHS=( … ) assignment in ${installer}"
	exit 1
}
# The eval hazard above, turned into a premise rather than left as prose: the
# extracted text has to be a lone array assignment with nothing that could
# chain a second command onto it.
[[ "${app_paths_decl}" =~ ^APP_PATHS=\([^\;\$\`\&\|\(\)]*\)$ ]] || {
	echo "FAIL: the APP_PATHS assignment in ${installer} is not a plain array literal, so evaluating it could run more than the assignment: ${app_paths_decl}"
	exit 1
}
declare -a APP_PATHS=()
eval "${app_paths_decl}"
((${#APP_PATHS[@]} > 0)) || {
	echo "FAIL: APP_PATHS in ${installer} evaluated to an empty array"
	exit 1
}

# ── The COPY sources ─────────────────────────────────────────────────────────

# Continuations are joined first: a COPY whose source and destination are split
# across a trailing `\` is one instruction, and parsing it per-line would read
# the source as a destination and drop it.
joined="$(sed -e ':a' -e '/\\$/{N;s/\\\n//;ba' -e '}' "${containerfile}")"

copy_sources=()
# Matched case-insensitively: Dockerfile instruction keywords are, so a
# lowercase `copy` is a real COPY that an uppercase-only pattern would skip
# without saying so. The configured hadolint does not flag one either, so this
# is the only thing standing between that spelling and a silent false negative.
# shellcheck disable=SC2312  # grep exits 1 on a Containerfile with no COPY at all; the empty-array check below is the handler
while IFS= read -r instruction; do
	# --from= copies out of an earlier build stage, not out of the build
	# context, so no manifest is involved. Lowercased for the same reason the
	# grep below is case-insensitive.
	if [[ "${instruction,,}" == *--from=* ]]; then
		continue
	fi
	read -r -a tokens <<<"${instruction}"
	# Drop the instruction word and every --flag; of what is left the last
	# token is the destination and the rest are sources.
	operands=()
	for token in "${tokens[@]:1}"; do
		if [[ "${token}" == --* ]]; then
			continue
		fi
		operands+=("${token}")
	done
	((${#operands[@]} >= 2)) || {
		echo "FAIL: cannot split sources from destination in: ${instruction}"
		exit 1
	}
	copy_sources+=("${operands[@]:0:${#operands[@]} - 1}")
done < <(printf '%s\n' "${joined}" | grep -Ei '^[[:space:]]*(COPY|ADD)[[:space:]]')

((${#copy_sources[@]} > 0)) || {
	echo "FAIL: parsed no COPY/ADD sources out of ${containerfile}"
	exit 1
}

# ── Resolution ───────────────────────────────────────────────────────────────

# A source ships when it, or any ancestor directory, is a manifest entry:
# nfpm ships ./container as a whole directory, which covers
# container/context-mode-package-lock.json without naming it.
ships() {
	local candidate="$1" entry
	shift
	while :; do
		for entry in "$@"; do
			[[ "${entry}" == "${candidate}" ]] && return 0
		done
		[[ "${candidate}" == */* ]] || return 1
		candidate="${candidate%/*}"
	done
}

unresolved=0
exempt=0
for copy_source in "${copy_sources[@]}"; do
	copy_source="${copy_source#./}"
	copy_source="${copy_source%/}"
	# shellcheck disable=SC2310  # `ships` returns 1 as an answer, not as an error; suspending set -e is the point
	if ships "${copy_source}" "${EXEMPT_SOURCES[@]}"; then
		exempt=$((exempt + 1))
		continue
	fi
	# Existence is checked after the exemption, never before it: configs/ is
	# generated at `riotbox build` time and legitimately absent from a
	# checkout. For everything else a source that is not in the repo at all is
	# a mistyped or deleted path, which the ancestor walk below would happily
	# resolve against the parent directory's manifest entry and never notice.
	if [[ ! -e "${repo_root}/${copy_source}" ]]; then
		echo "UNRESOLVED ${copy_source}: no such path in ${repo_root} — the COPY source is mistyped or was deleted, and no build here would catch it"
		unresolved=$((unresolved + 1))
		continue
	fi
	missing=""
	# shellcheck disable=SC2310  # same: a non-zero `ships` is the "not shipped" verdict this branch records
	ships "${copy_source}" "${nfpm_ships[@]}" || missing="nfpm.yaml contents"
	# shellcheck disable=SC2310  # same
	ships "${copy_source}" "${APP_PATHS[@]}" ||
		missing="${missing:+${missing} and }install.sh APP_PATHS"
	if [[ -n "${missing}" ]]; then
		echo "UNRESOLVED ${copy_source}: in the repo but not shipped by ${missing} — \`riotbox build\` from an installed tree would not find it"
		unresolved=$((unresolved + 1))
	fi
done

((unresolved == 0)) || {
	echo "FAIL: ${unresolved} COPY source(s) did not resolve — see the lines above"
	exit 1
}
echo "copy_manifest_coverage=pass (${#copy_sources[@]} sources, ${exempt} exempt)"
